seleniumGrid=true
gridURL=http://localhost:4444/wd/hub

#Application URL
#url_base = https://opensource-demo.orangehrmlive.com/
url_base = http://localhost/orangehrm/orangehrm-5.8.1/web/index.php/auth/login
url_grid = http://host.docker.internal/orangehrm/web/index.php/auth/login

#Browser Configuration
browser = chrome

#Credentials
#username = orangehrm_hverma
#password = Passw0rd@7654321

username = ashish
password = Test@8055507199

#ImplicitWait (in seconds)
implicitWait =30

#ExplicitWait
explicitWait = 30